Array.prototype.contains = function(element) {
	for (var i = 0; i < this.length; i++) {
		if (this[i] == element) return true;
	}
	return false;
}

String.prototype.trim = function() {
	return this.replace(/^\s+|\s+$/g,'');
}

// from http://www.ilfilosofo.com/blog/2008/04/14/addevent-preserving-this/
function addEvent(obj, type, fn) {
	if (obj.addEventListener) { // W3C standard
		obj.addEventListener(type, fn, false);
	}
	else if (obj.attachEvent) { // IE
		obj.attachEvent('on' + type, function() {return fn.call(obj, window.event);});
	}
}

function addClickEvent(elem, func, followLink) {
	// If the element has an onclick event handler already, capture it; otherwise create an empty anonymous function
	var oldonclick = (typeof elem.onclick == 'function') ? elem.onclick : function () {};
	// Set the element's onclick function to do the original function first, then the new one
	//alert("In addClickEvent(): " + elem);
	elem.onclick = function () {
		oldonclick(); // doesn't matter if original onclick had return true/false, though we could capture the result and override followLink if we wanted
		func(elem);
		return followLink;
	};
}

function getCookie(cookieName) {
	var cookies = document.cookie.split(';');
	for (var i = 0; i < cookies.length; i++) {
		var crumbs = cookies[i].split('=');
		if (crumbs[0].trim() == cookieName && cookies.length > 1) return unescape(crumbs[1].trim());
	}
	return null; // cookieName not found
}

function isSurveyTime() {
	// Build array of testing periods (start and stop); there should be twelve pairs, one per month for a year, but not all are known yet
	// mmm dd yyyy hh24:00 PST or PDT
	// PDT 2018: Ends November 4 2 am; PST until March 10 2019, when PDT starts again
	var testTimes = [
		[Date.parse("Jul 18 2018 15:00 PDT"), Date.parse("Jul 25 2018 23:59 PDT")]
	,	[Date.parse("Jul 31 2018 11:00 PDT"), Date.parse("Jul 31 2018 13:00 PDT")]
	,	[Date.parse("Aug 20 2018 17:00 PDT"), Date.parse("Aug 20 2018 19:00 PDT")]
	,	[Date.parse("Sep 19 2018 09:00 PDT"), Date.parse("Sep 19 2018 11:00 PDT")]
];
	var now = new Date().getTime();
	for (var testTime in testTimes) {
		var start = testTimes[testTime][0];
		var stop = testTimes[testTime][1];
		if ( (start <= now) && (now < stop) ) return true;
	}
	return false;
}

function isDomainSurveyable(link) {
	// Returns true if entire domain is eligible for survey, instead of just specific pages
	if (link == null) var link = window.location;
	var domain = link.hostname;
	// Do comparison without initial www, if present
	domain = domain.replace(/^www[.]/, '');
	var surveyable = false;
	var surveyableDomains = [
		'uclibs.org'
	,	'129.35.213.31'
	,	'129.35.248.48'
	,	'149.142.212.51'
	,	'170.225.184.107'
	,	'170.225.96.21'
	,	'170.225.99.9'
	,	'2facts.com'
	,	'360.datamonitor.com'
	,	'64.33.57.25'
	,	'66.98.205.91'
	,	'aacr.org'
	,	'aafp.org'
	,	'aanda.org'
	,	'aaojournal.org'
	,	'aapgbulletin.datapages.com'
	,	'aappublications.org'
	,	'aau.org'
	,	'abimperio.net'
	,	'academic.marketresearch.com'
	,	'academicmedicine.org'
	,	'access.rdatoolkit.org'
	,	'accessem.com'
	,	'accessengineeringlibrary.com'
	,	'accessible.com'
	,	'accessmedicine.com'
	,	'accesspharmacy.com'
	,	'accessscience.com'
	,	'accesssurgery.com'
	,	'accuweather.ap.org'
	,	'acpjc.org'
	,	'acponline.org'
	,	'ada.org'
	,	'adc.bmjjournals.com'
	,	'aeaweb.org'
	,	'aebnet.nl'
	,	'aemj.org'
	,	'afb.org'
	,	'africa-confidential.com'
	,	'africanstudiescompanion.com'
	,	'ag.arizona.edu'
	,	'agriculturenetbase.com'
	,	'ahajournals.org'
	,	'aiaa.org'
	,	'aidsinfo.nih.gov'
	,	'aidsonline.com'
	,	'aip.org'
	,	'airiti.com'
	,	'ajcn.org'
	,	'ajcp.ascpjournals.org'
	,	'ajkd.org'
	,	'ajnr.org'
	,	'ajph.org'
	,	'ajronline.org'
	,	'akkrt.hu'
	,	'alcoholism-cer.com'
	,	'alexanderstreet.com'
	,	'alexanderstreet2.com'
	,	'allafrica.com'
	,	'allenpress.com'
	,	'alpha.med.ege.edu.tr'
	,	'alphamedpress.org'
	,	'alternative-therapies.com'
	,	'aluka.org'
	,	'alzheimerjournal.com'
	,	'amamanualofstyle.com'
	,	'amdigital.co.uk'
	,	'amfar.org'
	,	'amjbot.org'
	,	'amjclinicaloncology.com'
	,	'amjforensicmedicine.com'
	,	'amjpathol.org'
	,	'ams.org'
	,	'anb.org'
	,	'ancestrylibrary.com'
	,	'ancientnarrative.com'
	,	'anesthesia-analgesia.org'
	,	'anesthesiology.org'
	,	'annallergy.org'
	,	'annals.org'
	,	'annalsnyas.org'
	,	'annalsofsurgery.com'
	,	'annclinlabsci.org'
	,	'annee-philologique.com'
	,	'annrheumdis.com'
	,	'annualreviews.org'
	,	'anthrosource.net'
	,	'anti-cancerdrugs.com'
	,	'antimicrobe.org'
	,	'ap.accuweather.com'
	,	'apa.org'
	,	'apabi.com'
	,	'aphapublications.org'
	,	'apimages.ap.org'
	,	'apimages.com'
	,	'app.harpweek.com'
	,	'app44.webinservice.com'
	,	'apt.rcpsych.org'
	,	'arba.odyssi.com'
	,	'arbor.revistas.csic.es'
	,	'archive.chosun.com'
	,	'archive.thenation.com'
	,	'areditions.com'
	,	'arl.org'
	,	'artfl-project.uchicago.edu'
	,	'artfl.uchicago.edu'
	,	'artflx.uchicago.edu'
	,	'artstor.org'
	,	'ashs.org'
	,	'asia-studies.com'
	,	'askzad.com'
	,	'asmedigitalcollection.asme.org'
	,	'aspetjournals.org'
	,	'astm.org'
	,	'atozmapsonline.com'
	,	'ats.ucla.edu'
	,	'atsdr1.atsdr.cdc.gov'
	,	'atsjournals.org'
	,	'atypon-link.com'
	,	'avmajournals.avma.org'
	,	'barkov.uchicago.edu'
	,	'bccresearch.com'
	,	'bdsl-online.de'
	,	'bepress.com'
	,	'bergfashionlibrary.com'
	,	'berghahnbooksonline.com'
	,	'best-in-class.com'
	,	'bestpracticedatabase.com'
	,	'bestpracticedatabase.eapps.com'
	,	'bi-interactive.com'
	,	'biblio.ebiblioteka.ru'
	,	'biblioline.nisc.com'
	,	'bids.ac.uk'
	,	'biochemj.org'
	,	'biological-markers.com'
	,	'biologists.com'
	,	'biolreprod.org'
	,	'bioone.org'
	,	'biophysj.org'
	,	'biosciencenetbase.com'
	,	'bir.org.uk'
	,	'bjophthalmol.com'
	,	'bjp.rcpsych.org'
	,	'bjr.birjournals.org'
	,	'blackwell-synergy.com'
	,	'blake.lib.rochester.edu'
	,	'bloodjournal.hematologylibrary.org'
	,	'bloodjournal.org'
	,	'bmj.com'
	,	'bna.birds.cornell.edu'
	,	'books.mcgraw-hill.com'
	,	'booksinprint.com'
	,	'brepolis.net'
	,	'brillonline.nl'
	,	'britannica.com'
	,	'brjpharmacol.org'
	,	'bssaonline.org'
	,	'buddhism-dict.net'
	,	'buildinggreen.com'
	,	'businessmonitor.com'
	,	'businessnetbase.com'
	,	'bvdinfo.com'
	,	'ca.rand.org'
	,	'cabdirect.org'
	,	'cairn.info'
	,	'calhealth.org'
	,	'caliber.ucpress.net'
	,	'calico.org'
	,	'cambridgesoft.com'
	,	'cancercell.org'
	,	'catalog.princeton.edu'
	,	'catchword.com'
	,	'cba.org'
	,	'cc.columbia.edu'
	,	'cdl-sfx.hosted.exlibrisgroup.com'
	,	'cdlib.org'
	,	'cdn.els-cdn.com'
	,	'cebp.aacrjournals.org'
	,	'ceeol.com'
	,	'ceicdata.securities.com'
	,	'cell.com'
	,	'chadwyck.com'
	,	'chant.org'
	,	'charlestonco.com'
	,	'checkpoint.riag.com'
	,	'chemeducator.org'
	,	'chemind.org'
	,	'chemlibnetbase.com'
	,	'chemnetbase.com'
	,	'chestjournal.chestpubs.org'
	,	'chicagomanualofstyle.org'
	,	'chinadataonline.org'
	,	'chosun.excavation.co.kr'
	,	'chronicle.com'
	,	'ci.nii.ac.jp'
	,	'ciaonet.org'
	,	'cios.org'
	,	'cis.stat.ucla.edu'
	,	'civilengineeringnetbase.com'
	,	'clarku.edu'
	,	'classificationweb.net'
	,	'classiques-garnier.com'
	,	'classweb.loc.gov'
	,	'cleantechnetbase.com'
	,	'clinchem.org'
	,	'clinexprheumatol.org'
	,	'cma.ca'
	,	'cmes.techscience.com'
	,	'cnbksy.com'
	,	'cnki.en.eastview.com'
	,	'cnki.net'
	,	'cnki.zh.eastview.com'
	,	'cochranelibrary.com'
	,	'cogbehavneurol.com'
	,	'cogbib.mouton-content.com'
	,	'cognet.mit.edu'
	,	'colet.lib.uchicago.edu'
	,	'colet.uchicago.edu'
	,	'collegesource.org'
	,	'columbiagazetteer.org'
	,	'comp-index.com'
	,	'companiontophonology.com'
	,	'computer.org'
	,	'computernetbase.com'
	,	'computingreviews.com'
	,	'concentric-literature.url.tw'
	,	'conference-board.org'
	,	'content.karger.com'
	,	'conwaygreene.com'
	,	'cornell.mirror.aps.org'
	,	'cpa-apc.org'
	,	'cpadmin.riag.com'
	,	'crcjournals.com'
	,	'crcnetbase.com'
	,	'crcpress.com'
	,	'crl.edu'
	,	'cro2.org'
	,	'csa.com'
	,	'csa1.co.uk'
	,	'csa2.com'
	,	'csa3.com'
	,	'cshlp.org'
	,	'cshmonographs.org'
	,	'csiro.au'
	,	'dachengdata.com'
	,	'database.yomiuri.co.jp'
	,	'datagold.com'
	,	'db.saur.de'
	,	'dbpia.co.kr'
	,	'ddrs.psmedia.com'
	,	'degruyter.com'
	,	'degruyter.de'
	,	'dekker.com'
	,	'delphion.com'
	,	'dentalbytes.com'
	,	'dentalsuccess.com'
	,	'desktop.loc.gov'
	,	'dev.biologists.org'
	,	'developmentalcell.com'
	,	'diabetesjournals.org'
	,	'dialogatsite.com'
	,	'dictionaryofeconomics.com'
	,	'digidev.library.ucla.edu'
	,	'digital-dev.library.ucla.edu'
	,	'digital.library.ucla.edu'
	,	'digitalcommons.library.arizona.edu'
	,	'digitallibrary.sae.org'
	,	'digizeitschriften.de'
	,	'dmd.org'
	,	'dpf99.library.ucla.edu'
	,	'dram.nyu.edu'
	,	'dss-census.mednet.ucla.edu'
	,	'dukejournals.org'
	,	'dukeupress.edu'
	,	'dyabola.de'
	,	'e-enlightenment.com'
	,	'earthscape.org'
	,	'eastview.com'
	,	'ebmonline.org'
	,	'ebooks.abc-clio.com'
	,	'ebsco-content.com'
	,	'ebscohost.com'
	,	'ecoamericas.com'
	,	'economicsnetbase.com'
	,	'ecosal.org'
	,	'ecsdl.org'
	,	'edpsciences.org'
	,	'edreview.org'
	,	'edrs.com'
	,	'eena.alexanderstreet.com'
	,	'eenews.net'
	,	'ehrafarchaeology.yale.edu'
	,	'ehrafworldcultures.yale.edu'
	,	'ehu.es'
	,	'eiu.com'
	,	'ejb.org'
	,	'ejbiochem.org'
	,	'ejbjs.org'
	,	'eje.org'
	,	'ejournals.ebsco.com'
	,	'ejournals.unm.edu'
	,	'elecjoncol.org'
	,	'electricalengineeringnetbase.com'
	,	'elib.cs.berkeley.edu'
	,	'elis.sk'
	,	'els.net'
	,	'emarketer.com'
	,	'emboj.org'
	,	'emerald-library.com'
	,	'emeraldinsight.com'
	,	'ency-japan.com'
	,	'encykorea.com'
	,	'endocrinology-journals.org'
	,	'endojournals.org'
	,	'engineeringvillage2.org'
	,	'engnetbase.com'
	,	'entertainment.timesonline.co.uk'
	,	'environetbase.com'
	,	'envplan.com'
	,	'epub.org.br'
	,	'epubs.siam.org'
	,	'equinoxjournals.com'
	,	'eres.library.ucla.edu'
	,	'ereserves.library.ucla.edu'
	,	'ergonomicsnetbase.com'
	,	'erj.ersjournals.com'
	,	'esajournals.org'
	,	'esapubs.org'
	,	'etext.library.ucla.edu'
	,	'ets.umdl.umich.edu'
	,	'etsupp.com'
	,	'eureka.rlg.org'
	,	'europaworld.com'
	,	'eutils.ncbi.nlm.nih.gov'
	,	'evolutionary-ecology.com'
	,	'ewjm.com'
	,	'extenza-eps.com'
	,	'f1000biology.com'
	,	'f1000medicine.com'
	,	'factiva.com'
	,	'familiesinsociety.org'
	,	'fasebj.org'
	,	'faulkner.com'
	,	'fda.gov'
	,	'ffas.usda.gov'
	,	'firstsearch.oclc.org'
	,	'fold3.com'
	,	'foodnetbase.com'
	,	'footnote.com'
	,	'foreignaffairs.org'
	,	'forensicnetbase.com'
	,	'freedoniagroup.com'
	,	'frontera-play.library.ucla.edu'
	,	'fundingopps.cos.com'
	,	'galegroup.com'
	,	'galenet.com'
	,	'galenet.gale.com'
	,	'gartner.library.ucla.edu'
	,	'gateway.nlm.nih.gov'
	,	'gateway.ovid.com'
	,	'gbv.de'
	,	'geneletter.org'
	,	'genengnews.com'
	,	'genesdev.org'
	,	'genetics.org'
	,	'genome.org'
	,	'genomemedicine.com'
	,	'geographicresearch.com'
	,	'geoscienceworld.org'
	,	'gerontologyjournals.org'
	,	'gide.uchicago.edu'
	,	'gideononline.com'
	,	'gleeditions.com'
	,	'global-dental.com'
	,	'global.factiva.com'
	,	'globalbooksinprint.com'
	,	'globalfinancialdata.com'
	,	'globalfindata.com'
	,	'goldstandard.com'
	,	'grants.nih.gov'
	,	'greenwood.com'
	,	'greenwood.scbbs.com'
	,	'grolier.com'
	,	'groveart.com'
	,	'grovemusic.com'
	,	'groveopera.com'
	,	'gsajournals.org'
	,	'gsapubs.org'
	,	'gso.gbv.de'
	,	'guidetoreference.org'
	,	'guilfordjournals.com'
	,	'gut.bmjjournals.com'
	,	'gutenberg-e.org'
	,	'gwdg.de'
	,	'hadashot-esi.org.il'
	,	'haematologica.it'
	,	'haifa.ac.il'
	,	'hanszell.co.uk'
	,	'hapi.gseis.ucla.edu'
	,	'hapi.ucla.edu'
	,	'harrisonsonline.com'
	,	'haworthpress.com'
	,	'hbcpnetbase.com'
	,	'hc-sc.gc.ca'
	,	'hdl.handle.net'
	,	'hdl.lib.umich.edu'
	,	'health.gov.au'
	,	'healthaffairs.org'
	,	'heartjnl.com'
	,	'heinonline.org'
	,	'hepg.org'
	,	'hh.um.es'
	,	'highwire.org'
	,	'highwire.stanford.edu'
	,	'hipeac.net'
	,	'hiperkitap.com'
	,	'histories.cambridge.org'
	,	'historycooperative.org'
	,	'hkam.org.hk'
	,	'homepage.data-planet.com'
	,	'hood2.ei.org'
	,	'hospitalpracticemed.com'
	,	'hosppract.com'
	,	'hpq.press.illinois.edu'
	,	'hsph.harvard.edu'
	,	'hsus.cambridge.org'
	,	'hti.umich.edu'
	,	'huc.edu'
	,	'humanities.uchicago.edu'
	,	'humankinetics.com'
	,	'hw.oeaw.ac.at'
	,	'hwwilsonweb.com'
	,	'iaor-palgrave.com'
	,	'ibisworld.com'
	,	'icadb.princeton.edu'
	,	'icevirtuallibrary.com'
	,	'icpsr.umich.edu'
	,	'icsd.fiz-karlsruhe.de'
	,	'icsdweb.fiz-karlsruhe.de'
	,	'idc.nl'
	,	'idealibrary.com'
	,	'idoican.com.cn'
	,	'idpr.org.uk'
	,	'ieeexplore.ieee.org'
	,	'ielimg.ihs.com'
	,	'igi-global.com'
	,	'ijga.agu.org'
	,	'ijs.sgmjournals.org'
	,	'imdatabases.library.utoronto.ca'
	,	'imfstatistics.org'
	,	'immunity.com'
	,	'immunology.org'
	,	'indiastat.com'
	,	'industrialnetbase.com'
	,	'infoed.org'
	,	'infopoems.com'
	,	'informa.com'
	,	'informahealthcare.com'
	,	'informaworld.com'
	,	'infosecuritynetbase.com'
	,	'infotrac.galegroup.com'
	,	'infoweb.newsbank.com'
	,	'ingenta.com'
	,	'ingentaconnect.com'
	,	'inquiryjournal.org'
	,	'int-res.com'
	,	'intarch.ac.uk'
	,	'intelliconnect.cch.com'
	,	'intlpress.com'
	,	'iop.org'
	,	'iopscience.iop.org'
	,	'iovs.org'
	,	'ipap.jp'
	,	'ipm.academiccharts.com'
	,	'ippnw.org'
	,	'irishnewsarchive.com'
	,	'ishib.org'
	,	'isiknowledge.com'
	,	'isla.lmi.net'
	,	'itergateway.org'
	,	'itknowledgebase.net'
	,	'iucr.org'
	,	'iumj.indiana.edu'
	,	'iwaponline.com'
	,	'jamanetwork.com'
	,	'jamia.org'
	,	'jaoa.org'
	,	'jasn.org'
	,	'jbc.org'
	,	'jbiol.com'
	,	'jbmronline.org'
	,	'jcb.org'
	,	'jchemed.chem.wisc.edu'
	,	'jci.org'
	,	'jclinrheum.com'
	,	'jco-online.com'
	,	'jco.ascopubs.org'
	,	'jco.org'
	,	'jcs.biologists.org'
	,	'jdentaled.org'
	,	'jeb.biologists.org'
	,	'jem.org'
	,	'jendocrinolinvest.it'
	,	'jewishreviewofbooks.com'
	,	'jgp.org'
	,	'jhc.org'
	,	'jhep.mse.jhu.edu'
	,	'jhr.uwpress.org'
	,	'jidonline.org'
	,	'jiesonline.com'
	,	'jimmunol.org'
	,	'jjphysiol.jstage.jst.go.jp'
	,	'jleukbio.org'
	,	'jlr.org'
	,	'jneurosci.org'
	,	'jnm.snmjournals.org'
	,	'jnnp.com'
	,	'jodi.ecs.soton.ac.uk'
	,	'joim.com'
	,	'joionline.org'
	,	'jopdentonline.org'
	,	'joponline.org'
	,	'jospt.org'
	,	'journal.co.nz'
	,	'journalofpediatricophthalmology.com'
	,	'journals.ametsoc.org'
	,	'journals.asha.org'
	,	'journals.asm.org'
	,	'journals.brepols.net'
	,	'journals.cambridge.org'
	,	'journals.cms.math.ca'
	,	'journals.endocrinology.org'
	,	'journals.royalsociety.org'
	,	'journals.sfu.ca'
	,	'journals.uchicago.edu'
	,	'journalsleep.org'
	,	'journalsonline.tandf.co.uk'
	,	'jove.com'
	,	'jp.physoc.org'
	,	'jpet.org'
	,	'jpgn.org'
	,	'jrheum.org'
	,	'jsad.com'
	,	'jspinaldisorders.com'
	,	'jstor.org'
	,	'jtrauma.com'
	,	'jucs.org'
	,	'jultrasoundmed.org'
	,	'kapis1.wkap.nl'
	,	'keesings.com'
	,	'kiss.kstudy.com'
	,	'klassiker.chadwyck.com'
	,	'kluweronline.com'
	,	'knovel.com'
	,	'knowledgeexpress.com'
	,	'kompass-usa.com'
	,	'kompass.com'
	,	'koreaa2z.com'
	,	'krpia.co.kr'
	,	'kstudy.com'
	,	'kurtis.it'
	,	'ladb.unm.edu'
	,	'landesbioscience.com'
	,	'latinnews.com'
	,	'leaonline.com'
	,	'learnmem.org'
	,	'lexika.tanto.de'
	,	'lexisnexis.com'
	,	'lib.uchicago.edu'
	,	'librapharm.co.uk'
	,	'library.cqpress.com'
	,	'library.marketlineinfo.com'
	,	'library.nlx.com'
	,	'library.seg.org'
	,	'library.uiuc.edu'
	,	'library.utoronto.ca'
	,	'library.yorku.ca'
	,	'libraryissues.com'
	,	'licensed.cdlib.org'
	,	'liebertonline.com'
	,	'liebertpub.com'
	,	'lis.uiuc.edu'
	,	'litguide.press.jhu.edu'
	,	'locatorplus.gov'
	,	'locus.siam.org'
	,	'lunaimaging.com'
	,	'lwwonline.com'
	,	'lyellcollection.org'
	,	'machaut.uchicago.edu'
	,	'magazineresearchcenter.com'
	,	'mankindquarterly.org'
	,	'marketline.com'
	,	'massey.ac.nz'
	,	'materialconnexion.com'
	,	'materialsnetbase.com'
	,	'mathjournals.org'
	,	'mathnetbase.com'
	,	'mcponline.org'
	,	'mdconsult.com'
	,	'mdx.com'
	,	'mechanicalengineeringnetbase.com'
	,	'medicalletter.org'
	,	'medlet-best.securesites.com'
	,	'melvyl.cdlib.org'
	,	'mend.endojournals.org'
	,	'mergent.com'
	,	'mergenthorizon.com'
	,	'mergentkbr.com'
	,	'mergentonline.com'
	,	'metapress.com'
	,	'mganet.org'
	,	'mhmedical.com'
	,	'mic.sgmjournals.org'
	,	'micromedex.com'
	,	'micromedexsolutions.com'
	,	'militarynetbase.com'
	,	'minsocam.org'
	,	'mitpressjournals.org'
	,	'mlajournals.org'
	,	'molbiolcell.org'
	,	'molbiolevol.org'
	,	'molecule.org'
	,	'molpharm.org'
	,	'morganclaypool.com'
	,	'mosbynursingskills.com'
	,	'mrlonline.org'
	,	'mrs.org'
	,	'multidataonline.com'
	,	'multilingual-matters.net'
	,	'mup.man.ac.ak'
	,	'muse.jhu.edu'
	,	'musicalamerica.com'
	,	'na.jkn21.com'
	,	'nanonetbase.com'
	,	'nationaljournal.com'
	,	'naturalstandard.com'
	,	'nature.com'
	,	'naxosmusiclibrary.com'
	,	'nber.org'
	,	'ncbi.nlm.nih.gov'
	,	'ncte.org'
	,	'nejm.org'
	,	'neoreviews.aapjournals.org'
	,	'netadvantage.standardandpoors.com'
	,	'netlibrary.com'
	,	'neurology.org'
	,	'neurosciencenetbase.com'
	,	'new-media-and-society.com'
	,	'newamamanualofstyle.com'
	,	'newisiknowledge.com'
	,	'newleftreview.org'
	,	'nii.ac.jp'
	,	'nmanet.org'
	,	'noaa.gov'
	,	'nowpublishers.com'
	,	'nrc.ca'
	,	'nrcresearchpress.com'
	,	'nt12.orbital.net'
	,	'ntrlr3.ntis.gov'
	,	'nurimedia.co.kr'
	,	'nurseweek.com'
	,	'nursing.gr'
	,	'nursingworld.org'
	,	'nutrition.cabweb.org'
	,	'nutrition.org'
	,	'nutritionnetbase.com'
	,	'nybooks.com'
	,	'obesityresearch.org'
	,	'occenvmed.com'
	,	'occup-healthandsafetynetbase.com'
	,	'oeb.griffith.ox.ac.uk'
	,	'oecd-ilibrary.org'
	,	'oed.com'
	,	'oldenbourg-link.com'
	,	'ommbid.com'
	,	'online.issn.org'
	,	'online.sagepub.com'
	,	'opticsinfobase.org'
	,	'oriprobe.com'
	,	'ornl.gov'
	,	'osa.org'
	,	'oup.co.uk'
	,	'oupjournals.org'
	,	'oxfordartonline.com'
	,	'oxforddnb.com'
	,	'oxfordeconomics.com'
	,	'oxfordhandbooks.com'
	,	'oxfordislamicstudies.com'
	,	'oxfordjournals.org'
	,	'oxfordmusiconline.com'
	,	'oxfordreference.com'
	,	'oxfordscholarship.com'
	,	'palgrave-journals.com'
	,	'papers.nber.org'
	,	'pb.rcpsych.org'
	,	'pbr.psychonomic-journals.org'
	,	'pdcnet.org'
	,	'pediatricnursing.org'
	,	'pediatrics.org'
	,	'pedresearch.org'
	,	'pedsinreview.aapjournals.org'
	,	'perceptionweb.com'
	,	'perio.org'
	,	'pharmaceuticalnetbase.com'
	,	'pharmrev.aspetjournals.org'
	,	'philologic.uchicago.edu'
	,	'phycologia.org'
	,	'physicsnetbase.com'
	,	'physiology.org'
	,	'physsportsmed.com'
	,	'pinatubo.ucop.edu'
	,	'pjm.math.berkeley.edu'
	,	'planningreport.com'
	,	'plantcell.org'
	,	'plantphysiol.org'
	,	'plantsciencenetbase.com'
	,	'plasreconsurg.com'
	,	'plunkettonline.com'
	,	'plunkettresearch.com'
	,	'plunkettresearchonline.com'
	,	'plunkettsonline.com'
	,	'pnas.org'
	,	'poj.peeters-leuven.be'
	,	'policymap.com'
	,	'polymersdatabase.com'
	,	'poolesplus.odyssi.com'
	,	'portal.acm.org'
	,	'portal.euromonitor.com'
	,	'portico.org'
	,	'portlandpress.com'
	,	'postgradmed.com'
	,	'postgradmedj.com'
	,	'press.uiuc.edu'
	,	'primarysourcesonline.nl'
	,	'private.programmers.ucla.edu'
	,	'private.www.sscnet.ucla.edu'
	,	'privco.com'
	,	'prl5.sdsc.edu'
	,	'products.asminternational.org'
	,	'projecteuclid.org'
	,	'projectmanagementnetbase.com'
	,	'proquest.com'
	,	'proquest.safaribooksonline.com'
	,	'proquestreference.com'
	,	'proteinscience.org'
	,	'proteome.com'
	,	'prsgroup.com'
	,	'psychiatrist.com'
	,	'psychiatryonline.com'
	,	'psychiatryonline.org'
	,	'ptjournal.org'
	,	'publicadministrationnetbase.com'
	,	'publications.chestnet.org'
	,	'publish.aps.org'
	,	'publishing.cdlib.org'
	,	'pubs.acs.org'
	,	'pubs.ama-assn.org'
	,	'pubs.amstat.org'
	,	'pubs.nrc-cnrc.gc.ca'
	,	'pubsonline.informs.org'
	,	'qjps.com'
	,	'quercus.igpp.ucla.edu'
	,	'quintpub.com'
	,	'quod.lib.umich.edu'
	,	'radiographics.rsnajnls.org'
	,	'radiology.rsnajnls.org'
	,	'raes.org.uk'
	,	'randstatestats.org'
	,	'rcjournal.com'
	,	'rdatoolkit.org'
	,	'reaxys.com'
	,	'reference-global.com'
	,	'referencecorp.com'
	,	'referenceworks.brillonline.com'
	,	'refuniv.odyssi.com'
	,	'refworks.reference-global.com'
	,	'residentandstaff.com'
	,	'reutersbusinessinsight.com'
	,	'revista-iberoamericana.pitt.edu'
	,	'rhe.eu.com'
	,	'ria.ie'
	,	'ria.thomson.com'
	,	'rmp.aps.org'
	,	'rnajournal.org'
	,	'rocksbackpages.com'
	,	'romanistudies.org'
	,	'ropercenter.uconn.edu'
	,	'routledge.com'
	,	'routledgereligiononline.com'
	,	'rsc.org'
	,	'rsmjournals.com'
	,	'rspb.royalsocietypublishing.org'
	,	'sabinet.co.za'
	,	'safari.informit.com'
	,	'safari.oreilly.com'
	,	'safundi.com'
	,	'sage-ereference.com'
	,	'sagepub.com'
	,	'samed.com'
	,	'samj.org.za'
	,	'sbrnet.com'
	,	'schattauer.de'
	,	'schiller.chadwyck.com'
	,	'scholar.google.com'
	,	'sci-technetbase.com'
	,	'sciamarchive.org'
	,	'science.uwaterloo.ca'
	,	'sciencedirect.com'
	,	'sciencemag.org'
	,	'sciencenews.org'
	,	'scifinder.cas.org'
	,	'scijournals.org'
	,	'sciverse.com'
	,	'scopus.com'
	,	'sd-editions.com'
	,	'search.epnet.com'
	,	'search.marquiswhoswho.com'
	,	'search.rdsinc.com'
	,	'secure.peeters-leuven.be'
	,	'serials.abc-clio.com'
	,	'serialssolutions.com'
	,	'shipindex.org'
	,	'siku.ad.sdsc.edu'
	,	'simplymap.com'
	,	'sinica.edu.tw'
	,	'site.ebrary.com'
	,	'site.securities.com'
	,	'slavery.amdigital.co.uk'
	,	'sma.org'
	,	'smf4.emath.fr'
	,	'soci.org'
	,	'socialexplorer.com'
	,	'software.chem.ucla.edu'
	,	'sourceoecd.org'
	,	'spie.org'
	,	'spiedigitallibrary.org'
	,	'spiedl.org'
	,	'spleen.uchicago.edu'
	,	'springer.com'
	,	'springerlink.com'
	,	'springeronline.com'
	,	'springerprotocols.com'
	,	'spuc.egreenapple.com'
	,	'ssrn.com'
	,	'stacks.iop.org'
	,	'stat-usa.gov'
	,	'statab.conquestsystems.com'
	,	'statref.com'
	,	'statsnetbase.com'
	,	'stemcells.alphamedpress.org'
	,	'stephanus.tlg.uci.edu'
	,	'stke.sciencemag.org'
	,	'strauss.library.ucla.edu'
	,	'structure.org'
	,	'subscriber.pagesuite-profess'
	,	'taiwanclassic.com'
	,	'tandf.co.uk'
	,	'tandfonline.com'
	,	'tapor.library.utoronto.ca'
	,	'tax.cchgroup.com'
	,	'taylorandfrancis.com'
	,	'tbrc.org'
	,	'telecommunicationsnetbase.com'
	,	'textilenetbase.com'
	,	'the-tls.co.uk'
	,	'thecochranelibrary.com'
	,	'thejns.org'
	,	'theoncologist.alphamedpress.org'
	,	'thieme-chemistry.com'
	,	'thieme-connect.com'
	,	'thieme.com'
	,	'thomastelford.com'
	,	'thomsonhc.com'
	,	'thorax.bmjjournals.com'
	,	'thoraxjnl.com'
	,	'tmsoc.org'
	,	'tol.cz'
	,	'toxicologynetbase.com'
	,	'transfusion.org'
	,	'tribologynetbase.com'
	,	'turpion.org'
	,	'tvnews.vanderbilt.edu'
	,	'twst.com'
	,	'uair.arizona.edu'
	,	'uc-dev.worldcat.org'
	// ,	'ucill.cdlib.org'
	,	'ucla.naxosmusiclibrary.com'
	,	'ucla.uniworldbp.com'
	,	'uclosangeles.classical.com'
	,	'uclosangeles2.classical.com'
	,	'uclosangeles4.classical.com'
	,	'ucpress.edu'
	,	'udndata.com'
	,	'ulrichsweb.com'
	,	'umdl.umich.edu'
	,	'umi.com'
	,	'unige.ch'
	,	'universitypublishingonline.org'
	,	'untreaty.un.org'
	,	'updateusa.com'
	,	'uptodate.com'
	,	'vandenhoeck-ruprecht.de'
	,	'vertigomagazine.co.uk'
	,	'vet.cabweb.org'
	,	'veterinaryrecord.bvapublications.com'
	,	'vir.sgmjournals.org'
	,	'visualdx.com'
	,	'wanfangdata.com'
	,	'water.usgs.gov'
	,	'waternetbase.com'
	,	'wbaonline.co.uk'
	,	'web.lexis-nexis.com'
	,	'web.nichigai.co.jp'
	,	'webcsd.ccdc.cam.ac.uk'
	,	'webofknowledge.com'
	,	'webreports.net'
	,	'webspirs.silverplatter.com'
	,	'wef.org'
	,	'whitston.com'
	,	'wiley.com'
	,	'wisenews.wisers.net'
	,	'wkhealth.com'
	,	'wnc.dialog.com'
	,	'worldbank.org'
	,	'worldoflearning.com'
	,	'worldscinet.com'
	,	'worldshakesbib.org'
	,	'wwp.brown.edu'
	,	'www-fourier.ujf-grenoble.fr'
	,	'xipolis.net'
	,	'zephyr.bvdep.com'
	,	'zephyrdealdata.com'
	];
	if (surveyableDomains.contains(domain)) surveyable = true;
	return surveyable;
}
	
function isLibraryDomain(domain) {
	// Returns true if domain contains library.ucla.edu (case insensitive)
	return(domain.toUpperCase().indexOf('LIBRARY.UCLA.EDU') >= 0);
}

function redirectLink(link) {
	var href = link.href;
	if (! href) return false;
	href = escape(href);
	var target = 'http://unitproj.library.ucla.edu/lis/libweb/lcas_router.cfm';
	target += '?target=' + href;
	// alert('DEBUG: Target ' + target);
	window.location = target;
}
  
function hookLinks() {
	var thisDomain = window.location.hostname;
	var links = document.getElementsByTagName("a");
	for (var i = 0; i < links.length; i++) {
		var link = links[i];
		// IE has problems with some possibly-invalid links which real browsers can  handle, so check and skip if needed
		try {
			var domain = link.hostname;
			// bail out on special cases
			if (domain == null) continue;
			// hook into surveyable links, but exclude ones on the same domain
			if ( isDomainSurveyable(link) && (thisDomain != domain) ) {
				// alert('DEBUG: Adding click event for ' + link);
				addClickEvent(link, redirectLink, false); // addClickEvent adds call to redirectLink(link) to click event
			}
			// addEvent(link, 'click', redirectLink); //works, except link is still followed
			// Can't use generic addEvent() because we need to change link.onclick, not just add a new event to it
			// Must ensure that onclick returns false so the original link is not followed
		}
		catch (e) {} // we don't care about the error, just want to keep it from breaking things
	}
}

// If it's time for the survey, hook relevant links to redirect to the survey system
if (isSurveyTime() ) {
	// If this is a library page we care about, and survey cookies aren't already set, redirect to the survey
	// 2014: I think this is no longer relevant as we're not surveying library pages themselves, but links on them...
	if ( isDomainSurveyable()  && (! getCookie('LIBCOSTSURVEY_EXPIRES') || ! getCookie('LIBCOSTSURVEY_SESSIONID'))) {
		redirectLink(parent.location); // pick up framed content correctly, instead of window.location which is current frame only
	}

	// alert("DEBUG: It's survey time!");
	addEvent(window, 'load', hookLinks);
	
	// Override function from Ex Libris highLight.js file; theirs breaks our link hooking
	// But only override during survey time
	highlightRecordDisplay = function(searchTerms) {
		return false;
	}
}
